### ISSUE TITLE
[Improvement] Half-Float (16 bit float) data type

### ISSUE THREAD

**Issue by PyroDevil** [WerWolv/PatternLanguage#11]
Some file formats, often related to game engines and applications related to computer graphics, use [16 bit floating point types](https://en.wikipedia.org/wiki/Half-precision_floating-point_format) (see [uses section](https://en.wikipedia.org/wiki/Half-precision_floating-point_format#Uses_of_half_precision)).

It is a standardized format and IMO support for decoding this type in the core language would make sense.

**Comment by WerWolv** [comment]
Hey!
While there's no direct support for 16 bit floats in the language, we do have a type for it in the [types library](https://github.com/WerWolv/ImHex-Patterns/blob/master/includes/type/float16.pat). In ImHex you can download it from the Content Store and then use `#include <type/float16.pat>` to include it
