### ISSUE TITLE
std::mem::copy_value_to_section affects value of function parameter

### ISSUE THREAD

**Issue by Hikodroid** [WerWolv/PatternLanguage#130]
After using copy_value_to_section, with an (auto?) array function parameter as the value, the contents of that value are affected in strange ways. Consider the following example:
```
import std.io;
import std.mem;

fn copyAscending(auto array, std::mem::Section section) {
    std::print("Ascending...");

    for (u8 i = 0, i < 0x0E, i = i + 1) {
        std::print("before#{}={:#x}", i, array[i].value);
    }

    for (s8 i = 0, i < 0x0E, i = i + 1) {
        std::mem::copy_value_to_section(array[i], section, i);
    }

    for (u8 i = 0, i < 0x0E, i = i + 1) {
        std::print("after#{}={:#x}", i, array[i].value);
    }
};

fn copyDescending(auto array, std::mem::Section section) {
    std::print("Descending...");

    for (u8 i = 0, i < 0x0E, i = i + 1) {
        std::print("before#{}={:#x}", i, array[i].value);
    }

    for (s8 i = 0x0D, i >= 0, i = i - 1) {
        std::mem::copy_value_to_section(array[i], section, i);
    }

    for (u8 i = 0, i < 0x0E, i = i + 1) {
        std::print("after#{}={:#x}", i, array[i].value);
    }
};

std::mem::Section testSectionAscending = std::mem::create_section("testSectionAscending");
std::mem::Section testSectionDescending = std::mem::create_section("testSectionDescending");

struct Value {
    u8 value;
};

struct Test {
    Value testArray[0x0E];
    copyAscending(testArray, testSectionAscending);
    copyDescending(testArray, testSectionDescending);
};

Test test @ 0x00;

std::print("Second try...");

for (u8 i = 0, i < 0x0E, i = i + 1) {
    std::print("second_before#{}={:#x}", i, test.testArray[i].value);
}

std::mem::Section testSectionAscending2 = std::mem::create_section("testSectionAscending2");
std::mem::Section testSectionDescending2 = std::mem::create_section("testSectionDescending2");

for (s8 j = 0, j < 0x0E, j = j + 1) {
    std::mem::copy_value_to_section(test.testArray[j], testSectionAscending2, j);
}

for (s8 k = 0x0D, k >= 0, k = k - 1) {
    std::mem::copy_value_to_section(test.testArray[k], testSectionDescending2, k);
}

for (u8 l = 0, l < 0x0E, l = l + 1) {
    std::print("second_after#{}={:#x}", l, test.testArray[l].value);
}
```
Which creates the following output:
```
I: Ascending...
I: before#0=0x11
I: before#1=0x22
I: before#2=0x33
I: before#3=0x44
I: before#4=0x55
I: before#5=0x66
I: before#6=0x77
I: before#7=0x88
I: before#8=0x99
I: before#9=0xaa
I: before#10=0xbb
I: before#11=0xcc
I: before#12=0xdd
I: before#13=0xee
I: after#0=0x0
I: after#1=0x0
I: after#2=0x0
I: after#3=0x0
I: after#4=0x0
I: after#5=0x0
I: after#6=0x0
I: after#7=0x0
I: after#8=0x0
I: after#9=0x0
I: after#10=0x0
I: after#11=0x0
I: after#12=0x0
I: after#13=0x0
I: Descending...
I: before#0=0x11
I: before#1=0x22
I: before#2=0x33
I: before#3=0x44
I: before#4=0x55
I: before#5=0x66
I: before#6=0x77
I: before#7=0x88
I: before#8=0x99
I: before#9=0xaa
I: before#10=0xbb
I: before#11=0xcc
I: before#12=0xdd
I: before#13=0xee
I: after#0=0x22
I: after#1=0x0
I: after#2=0x0
I: after#3=0x0
I: after#4=0x0
I: after#5=0x0
I: after#6=0x0
I: after#7=0x0
I: after#8=0x0
I: after#9=0x0
I: after#10=0x0
I: after#11=0x0
I: after#12=0x0
I: after#13=0x0
I: Second try...
I: second_before#0=0x11
I: second_before#1=0x22
I: second_before#2=0x33
I: second_before#3=0x44
I: second_before#4=0x55
I: second_before#5=0x66
I: second_before#6=0x77
I: second_before#7=0x88
I: second_before#8=0x99
I: second_before#9=0xaa
I: second_before#10=0xbb
I: second_before#11=0xcc
I: second_before#12=0xdd
I: second_before#13=0xee
I: second_after#0=0x11
I: second_after#1=0x22
I: second_after#2=0x33
I: second_after#3=0x44
I: second_after#4=0x55
I: second_after#5=0x66
I: second_after#6=0x77
I: second_after#7=0x88
I: second_after#8=0x99
I: second_after#9=0xaa
I: second_after#10=0xbb
I: second_after#11=0xcc
I: second_after#12=0xdd
I: second_after#13=0xee
I: Pattern exited with code: 0
I: Evaluation took 0.00636496s
```
As far as I can see this should result in sections that contain an exact copy of the source data, but the contents of testSectionAscending and testSectionDescending are weirdly shifted or partially missing. Also the output of the print statements should not be affected at all.
The test data is:
```
Hex View  00 01 02 03 04 05 06 07  08 09 0A 0B 0C 0D 0E 0F
 
00000000  11 22 33 44 55 66 77 88  99 AA BB CC DD EE      
```
testSectionAscending:
```
1100 0000 0000 0000 0000 0000 0000
```
testSectionDescending:
```
2222 3344 5566 7788 99aa bbcc ddee
```

**Comment by paxcut** [comment]
You are just missing a ref in the function declarations for the arrays
```cpp
fn copyAscending(ref auto array, std::mem::Section section) {
fn copyDescending(ref auto array, std::mem::Section section) {
```
with that it works like expected

**Comment by paxcut** [comment]
Explanation:

When passing arrays to functions passing by value doesn't tell the interpreter how big the array is so it doesn't copy the values correctly. By passing it by reference instead, you avoid the problem and the data is available in full. Beware that changes to the array will reflect back to the caller.

**Comment by paxcut** [comment]
I'm not sure why it behaves like that. One explanation could be that when passing parameters by value, the data copied is added to some variable somewhere that gets wiped out on garbage collection. Without the correct size for the data the behavior is really just undefined. 

As to how to handle this, every time you pass a parameter that is dynamically sized to a function, you need to pass it by reference. If you try to pass it by value operations on the data will not behave properly. This is mentioned in the documentation on the section of reference parameters.

**Comment by paxcut** [comment]
The entry about [[static]] does not deal with passing arguments by value vs. reference. It shows how dynamically and statically sized types can be treated very differently out of necessity. That entry is also a rare instance of the docs issuing a warning against wrong usage. The current documentation is a minimal description of the features that ImHex has so that one can get started using it and precious little else. 

You mentioned that you almost missed the issue, but how could you miss it when its effect on the computations is so evident? Figuring out why it isn't working is only a  post away either on the discord support server or here on GitHub through an issue or a discussion. The lack of documentation is complemented by a community that is almost always available and willing to help.

Passing dynamically allocated arguments by value is neither  a syntactic or a semantic  error. I don't know the exact technical details on how variables are handled when passed by value or by reference so I can't comment on ways to detect this at runtime.
