### ISSUE TITLE
s64 wrong value evaluation

### ISSUE THREAD

**Issue by ssmid** [WerWolv/PatternLanguage#19]
A value of 0x FFFF FFFF FFFF FFFF
parsed with
`s64 test @0x0;`
is detected as value 0x FFFF FFF**E** FFFF FFFF.
Probably a sign mistake?

ImHex Hex Editor v1.25.0

Edit: I hope this is the correct repository

Edit2: Great work, btw! ImHex with its pattern language makes it so much easier to reverse engineer file formats.

**Comment by WerWolv** [comment]
Hi! Sorry for ignoring this issue until now. I fixed this a while ago, everything should be fine now.

Thanks a lot :)
