### ISSUE TITLE
std::hash::crc32 documentation is out of date

### ISSUE THREAD

**Issue by mrozekma** [WerWolv/PatternLanguage#21]
The `std::hash::crc32` [documentation](https://imhex.werwolv.net/docs/libraries/std/std_hash.html) lists the function as having 4 parameters, but in c948558aecd56cf22c9b540bff8d37a547fe43e5 it was changed to 3 (`address` and `size` were combined into `pattern`).

**Comment by WerWolv** [comment]
You're correct, thank you!
