### ISSUE TITLE
lua54.hexpat segfaults in `Parser::parseStatements()` after fixing function parameter named `const`

### ISSUE THREAD

**Issue by Zaggy1024** [WerWolv/PatternLanguage#37]
While trying to fix up the lua54.hexpat file for bitfields, I ran into this issue loading `VLC/lua/extensions/VLSub.luac` from my VLC installation.

On [this line](https://github.com/WerWolv/PatternLanguage/blob/7d5b09965c6b89bbc0d5e3f0d74e33641cfc0a33/lib/source/pl/core/parser.cpp#L1696), `statement` is null.

**Comment by WerWolv** [comment]
I noticed this issue before too and fixed it. It shouldn't happen anymore when using the latest commit

**Comment by Zaggy1024** [comment]
Ah, good to know, I must be a few commits behind that then.

**Comment by Zaggy1024** [comment]
Confirmed fixed.
