### ISSUE TITLE
[Bug] Strange behavior on local variables in [[static]] structs

### ISSUE THREAD

**Issue by widberg** [WerWolv/PatternLanguage#44]
Consider the input

```plaintext
00 00
```

As expected, the pattern

```cpp
#include <std/sys.pat>

struct A {
    u8 a = 1;
    u8 b;
};

A a[2] @ 0x0;
std::assert(a[0].a == 1, "a[0].a != 1");
std::assert(a[1].a == 1, "a[1].a != 1");
```

evaluates fine and the assertions pass. However, if we make the struct A [[static]].

```cpp
#include <std/sys.pat>

struct A {
    u8 a = 1;
    u8 b; // If removed then the assertions pass
} [[static]];

A a[2] @ 0x0;
std::assert(a[0].a == 1, "a[0].a != 1");
std::assert(a[1].a == 1, "a[1].a != 1");
```

Then the first assertion passes but the second one fails. In fact, only the first member of an array of [[static]] structs will have the correct local variable values. All other members in the array will have 0 values for the local variables in my experience. If this is an intended optimization then perhaps the documentation could be updated to reflect this, since right now it only mentions layout in regards to [[static]].

Tested using PatternLanguage 57e89f6 (compiled from source, MSYS2) and ImHex 1.27.1 (Windows MSI Installer).

**Comment by WerWolv** [comment]
Thanks for the report, I improved the documentation on this now since these are issues due to the optimizations applied by the `[[static]]` attribute but they are to be expected. Static types are not allowed to use any things that need to be evaluated on a per-instance basis, otherwise the result will be undefined
