### ISSUE TITLE
Null-Pointer found in AST with recursive using declaration

### ISSUE THREAD

**Issue by brecert** [WerWolv/PatternLanguage#58]
The following snippet will cause `Invalid parser result: Null-Pointer found in AST`.
```cpp
using P<auto T> = P<T>;
```

The following snippet will cause ImHex to crash with `SIGSEGV`.
```cpp
using P<T> = P<T>;
```

**Comment by C3pa** [comment]
To confirm, in the latest release of ImHex (v1.34.0), the first issue still persists. The second snippet:
```c++
using P<T> = P<T>;
```
doesn't crash ImHex, but instead outputs:
```
E: error: Null-Pointer found in AST.
E:   -->   in <Source Code>:1:12
E: 1 | using P<T> = P<T>;
E:                ^

E: This is a parser bug. Please report it on GitHub.
```
