### ISSUE TITLE
Can't print big endian time, but works in little endian

### ISSUE THREAD

**Issue by rvanlaar** [WerWolv/PatternLanguage#63]
# expected result 

in big endian mode std::time::format should print the datetime

# current result
When printing a timestamp in big endian mode the printed value is "Invalid".

See the following pattern:

```
#pragma endian big

#include <std/string.pat>
#include <std/time.pat>

u32 datetime = 0xD6;

std::print("{}", std::time::format(std::time::to_utc(datetime)));
```

*note* Change `big` to `little` and it works.

**Comment by C3pa** [comment]
This issue doesn't exist in the latest release of ImHex (v1.34.0).

**Comment by paxcut** [comment]
This issue is almost 1 year old. If OP is still around please close it if it has been resolved indeed. Otherwise admins, please close this issue.

**Comment by rvanlaar** [comment]
Can confirm it works. Latest master July 8th 2024
