### ISSUE TITLE
Defines and attributes don't go together.

### ISSUE THREAD

**Issue by LennardF1989** [WerWolv/PatternLanguage#66]
Consider the following minimal example:

```
#define BASE_OFFSET = 48;

u8 componentBody[100] @ BASE_OFFSET [[color("0000FF")]];
```
BASE_OFFSET will throw an error like "Invalid function statement." - Also happens when done in structs.

If you remove the `color`-attribute, it works again.

```
u32 BASE_OFFSET = 48;

u8 componentBody[100] @ BASE_OFFSET [[color("0000FF")]];
```
Works just fine.

Not sure if intended.

**Comment by WerWolv** [comment]
Hey

Defines work the same as in C and C++. They're pure text replacements.
So everywhere you write `BASE_OFFSET` now it will be replaced with `= 48;` which is probably not what you want. Instead, use `#define BASE_OFFSET 48`
