### ISSUE TITLE
[Improvement] Displaying string from upper structure when hidden

### ISSUE THREAD

**Issue by gudzpoz** [WerWolv/PatternLanguage#9]
Well, this issue seems to belong to the ImHex repository, but I trace the actual implementation to `pl::Pattern::getChildren` here.

## Motivation / Expected behaviour

In many situations, people want to display formatted info about structs instead of their inner structure (or maybe they want both):

```
struct MAC {
	u8 octets[6] [[hidden]];
} [[format("mac_formatter")]];

fn mac_formatter(MAC mac) {
	return std::format("{0:02X}:{1:02X}:{2:02X}:{3:02X}:{4:02X}:{5:02X}",
		mac.octets[0],
		mac.octets[1],
		mac.octets[2],
		mac.octets[3],
		mac.octets[4],
		mac.octets[5]);
};

MAC mac @ 0;
```

![image](https://user-images.githubusercontent.com/14026120/182018226-dabd43a8-e359-40a7-a5b6-93acf4f6f984.png)

To avoid too much duplicate information, we can default structs to `[[hidden]]` and let the user explicitly set `[[hidden(false)]]`.

## Current behaviour

Struct info is never displayed in the hex editor. It seems patterns default to include themselves as their children. However, `struct`s and some other complex structures do not:

https://github.com/WerWolv/PatternLanguage/blob/1b0de5e85bd919c2b59f2eabce3ac91f629cebab/lib/include/pl/patterns/pattern.hpp#L129-L131
https://github.com/WerWolv/PatternLanguage/blob/1b0de5e85bd919c2b59f2eabce3ac91f629cebab/lib/include/pl/patterns/pattern_struct.hpp#L39-L48

So, `struct`s will never appear at all in the final flattened patterns or get displayed in the hex editor:

https://github.com/WerWolv/PatternLanguage/blob/1b0de5e85bd919c2b59f2eabce3ac91f629cebab/lib/source/pl/pattern_language.cpp#L239-L247

## P.S.

After adding struct itself to its children, things seem to be working somehow, despite that the displayed size of the struct appears to have a maximum of 16 bytes, which might belong to another issue, I suppose?

![image](https://user-images.githubusercontent.com/14026120/182018811-2b6e287a-7868-4cb1-bb9e-ec1103eb7b30.png)

```
struct A {
  u8 u[0x30];
};
```

**Comment by WerWolv** [comment]
Hi
I added a `[[sealed]]` attribute now for types to make them act like primitive types and not render their internal structure. Do you think that's enough for this?

About the highlighting only being a maximum of 16 bytes, this is a result of my optimized pattern searching. So far highlighted types only were able to be a maximum of 16 bytes so I only had to seach backwards 16 times to find all bytes a highlighted pattern could contain:

https://github.com/WerWolv/PatternLanguage/blob/master/lib/source/pl/pattern_language.cpp#L260-L274

Not quite sure yet how to go about fixing that.

**Comment by gudzpoz** [comment]
Yes, the new `[[sealed]]` attribute is beautiful.

As to the pattern searching, probably changing `m_flattenedPatterns` from `std::map<u64, std::vector<Pattern*>>` to [`IntervalTree<Pattern*>`](https://github.com/ekg/intervaltree) or [`boost::icl::interval_map<u64, std::vector<Pattern*>>` (user-implemented `operator+=` needed)](https://www.boost.org/doc/libs/1_79_0/libs/icl/doc/html/boost/icl/interval_map.html) should do?

**Comment by WerWolv** [comment]
Thanks a lot for this suggestion! I replaced the current implementation with an interval tree now so all these issues should be fixed :)
